version: "3"
services:
  postgres:
    container_name: nft-auction-demo-postgres
    build:
      context: docker-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=auctions
  #  networks:
  #    - hcs_heal
#    expose:
#      - "5432"
#    ports:
#      - "5432:5432"
#    command: -p 5432
    volumes:
      - ./docker-files/postgres-data:/var/lib/postgresql/data
  flyway:
    container_name: nft-auction-demo-flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/auctions
      - FLYWAY_SCHEMAS=public
      - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/hedera-nft-auction-demo-java-node/src/main/resources/migrations:/flyway/sql
    depends_on:
      - postgres

  node:
    container_name: nft-auction-demo-node
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      - AUCTION_NODE=true
      - REST_API=false
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo

  rest:
    container_name: hedera-nft-auction-demo-java-node
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      - REST_API=true
      - AUCTION_NODE=false
    env_file:
      - docker-files/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo
  ui:
    container_name: nft-auction-demo-ui
    build:
      context: hedera-nft-auction-demo-javascript-client
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - rest
