version: "3"
services:
  postgres-development:
    container_name: nft-auction-postgres-dev
    build:
      context: docker-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - ./docker-files/postgres-data:/var/lib/postgresql/data
    profiles:
      - dev

  postgres-production:
    container_name: nft-auction-postgres-prod
    image: ghcr.io/hashgraph/hedera-nft-auction-demo/nft-auction-postgres:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - ./docker-files/postgres-data:/var/lib/postgresql/data
    profiles:
      - prod

  node-development:
    container_name: nft-auction-node-dev
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      # Database connection
      - DATABASE_URL=postgresql://postgres-development:5433/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - POOL_SIZE=10
      # Run auction node only
      - AUCTION_NODE=true
      - REST_API=false
      - ADMIN_API=false
    env_file:
      - docker-files/.env
    depends_on:
      - postgres-development
    volumes:
      - ./docker-files:/demo
    profiles:
      - dev

  node-production:
    container_name: nft-auction-node-prod
    image: ghcr.io/hashgraph/hedera-nft-auction-demo/hedera_nft_auction_java_node:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      # Database connection
      - DATABASE_URL=postgresql://postgres-production:5433/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - POOL_SIZE=10
      # Run auction node only
      - AUCTION_NODE=true
      - REST_API=false
      - ADMIN_API=false
    env_file:
      - docker-files/.env
    depends_on:
      - postgres-production
    volumes:
      - ./docker-files:/demo
    profiles:
      - prod

  rest-development:
    container_name: nft-auction-node-api-dev
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      # Run API only
      - REST_API=true
      - ADMIN_API=true
      - AUCTION_NODE=false
      # Database connection
      - DATABASE_URL=postgresql://postgres-development:5433/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - POOL_SIZE=10
      # REST API Ports
      - VUE_APP_API_PORT=8081
      - API_VERTICLE_COUNT=16
      - ADMIN_API_PORT=8082
      - ADMIN_API_VERTICLE_COUNT=1
    env_file:
      - docker-files/.env
    ports:
      - "8081:8081"
# comment to hide the admin api outside the docker component (recommended in production)
      - "8082:8082"
    depends_on:
      - postgres-development
    volumes:
      - ./docker-files:/demo
    profiles:
      - dev

  rest-production:
    container_name: nft-auction-node-api-prod
    image: ghcr.io/hashgraph/hedera-nft-auction-demo/hedera_nft_auction_java_node:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      # Run API only
      - REST_API=true
      - ADMIN_API=true
      - AUCTION_NODE=false
      # Database connection
      - DATABASE_URL=postgresql://postgres-production:5433/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - POOL_SIZE=10
      # REST API Ports
      - VUE_APP_API_PORT=8081
      - API_VERTICLE_COUNT=16
      - ADMIN_API_PORT=8082
      - ADMIN_API_VERTICLE_COUNT=1
    env_file:
      - docker-files/.env
    ports:
      - "8081:8081"
      # comment to hide the admin api outside the docker component (recommended in production)
      - "8082:8082"
    depends_on:
      - postgres-production
    volumes:
      - ./docker-files:/demo
    profiles:
      - prod

  ui-development:
    container_name: nft-auction-ui-dev
    build:
      context: hedera-nft-auction-demo-javascript-client
    restart: unless-stopped
    env_file:
      - docker-files/.env
    ports:
      - "8080:8080"
    depends_on:
      - rest-development
    profiles:
      - dev

  ui-production:
    container_name: nft-auction-ui-prod
    build:
      context: hedera-nft-auction-demo-javascript-client
    restart: unless-stopped
    env_file:
      - docker-files/.env
    ports:
      - "8080:8080"
    depends_on:
      - rest-production
    profiles:
      - prod
