version: "3"
services:
  postgres:
    container_name: nft-auction-demo-postgres
    build:
      context: docker-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=auctions
  #  networks:
  #    - hcs_heal
#    expose:
#      - "5432"
#    ports:
#      - "5432:5432"
#    command: -p 5432
    volumes:
      - ./docker-files/postgres-data:/var/lib/postgresql/data

  node:
    container_name: nft-auction-demo-node
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      - AUCTION_NODE=true
      - REST_API=false
      - ADMIN_API=false
    env_file:
      - docker-files/.env
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo

  rest:
    container_name: hedera-nft-auction-demo-java-node
    build:
      context: hedera-nft-auction-demo-java-node
    restart: unless-stopped
    environment:
      - REST_API=true
      - ADMIN_API=true
      - AUCTION_NODE=false
    env_file:
      - docker-files/.env
    ports:
      - "8081:8081"
# uncomment to expose the admin api outside the docker component (not recommended)
#      - "8082:8082"
    depends_on:
      - postgres
    volumes:
      - ./docker-files:/demo
  ui:
    container_name: nft-auction-demo-ui
    build:
      context: hedera-nft-auction-demo-javascript-client
    restart: unless-stopped
    env_file:
      - docker-files/.env
    ports:
      - "8080:8080"
    depends_on:
      - rest
