version: 2.1

references:
  workspace_root: &workspace_root /tmp/workspace

  # Docker images
  docker_jdk11: &docker_jdk14
    image: adoptopenjdk:14-jdk-hotspot

commands:
  persist_artifacts_to_workspace:
    steps:
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - artifacts

  install_openjdk_14:
    description: "Install OpenJDK 14"
    steps:
      - run:
          name: Install OpenJDK 14
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa \
            && sudo apt-get update -q \
            && sudo apt install -y openjdk-14-jdk

workflows:
  main:
    jobs:
      - build_gradle:
          filters: # required since `release_artifacts` has tag filters AND requires `this`
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build_ui:
          filters: # required since `release_artifacts` has tag filters AND requires `this`
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release_artifacts:
          requires:
            - build_gradle
            - build_ui
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

jobs:
  build_gradle:
    environment:
      WORKSPACE: *workspace_root
    docker:
      - *docker_jdk14
    steps:
      - checkout
        name: Running gradle build
        working_directory: "hedera-nft-auction-demo-java-node"
        command: ./gradlew build
      - store_artifacts:
          path: hedera-nft-auction-demo-java-node/build/reports
          destination: /surefire
      - store_test_results:
          path: hedera-nft-auction-demo-java-node/build/reports
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - persist_artifacts_to_workspace

  integration_test:
    environment:
      WORKSPACE: *workspace_root
    docker:
      - *docker_jdk14
    steps:
      - checkout
      - run:
          name: Running gradle integration test
          working_directory: "hedera-nft-auction-demo-java-node"
          command: ./gradlew build integrationTest
      - store_artifacts:
          path: hedera-nft-auction-demo-java-node/build/reports
          destination: /surefire
      - store_test_results:
          path: hedera-nft-auction-demo-java-node/build/reports
      - run:
          name: Upload Code Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - persist_artifacts_to_workspace

  build_ui:
    environment:
      WORKSPACE: *workspace_root
    docker:
      - image: node:13.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "hedera-nft-auction-demo-javascript-client/package-lock.json" }}
            - npm-v1-{{ .Branch }}
            - npm-v1-
      - run:
          working_directory: "hedera-nft-auction-demo-javascript-client"
          name: Build UI
          command: yarn install
      - save_cache:
          key: npm-v1-{{ .Branch }}-{{ checksum "hedera-nft-auction-demo-javascript-client/package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
      - persist_artifacts_to_workspace

  release_artifacts:
    docker:
      - *docker_jdk14
    steps:
      - attach_workspace:
          at: *workspace_root
      - store_artifacts:
          path: /tmp/workspace/artifacts
