name: Docker Publish

on:
  release:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  workflow_dispatch:

env:
  JAVA_IMAGE_NAME: hedera_nft_auction_java_node
  JAVA_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/${{ JAVA_IMAGE_NAME }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push_java_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build java node image
        run: docker build . --file Dockerfile --tag ${{ JAVA_IMAGE_NAME }} --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: hedera-nft-auction-demo-java-node

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
               # Change all uppercase to lowercase
               IMAGE_ID=$(echo $JAVA_IMAGE_ID | tr '[A-Z]' '[a-z]')
               VERSION=latest
               echo IMAGE_ID=$IMAGE_ID
               echo VERSION=$VERSION
               docker tag $IMAGE_ID $IMAGE_ID:$VERSION
               docker push $IMAGE_ID:$VERSION
