name: Docker Publish

on:
  release:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  workflow_dispatch:

env:
  JAVA_IMAGE_NAME: hedera-nft-auction-demo-java-node

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push_java_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build java node image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/hedera-nft-auction-java-node:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/hedera-nft-auction-java-node:${{ github.ref }}
            docker.pkg.github.com/${{ github.repository }}/hedera-nft-auction-java-node:latest
        working-directory: hedera-nft-auction-demo-java-node
