# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Unit+Integration Tests

on:
  push:
     branches: [ master ]
  pull_request:
     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/hedera-nft-auction-demo-java-node/.gradle/caches
          ~/hedera-nft-auction-demo-java-node/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-`
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: cd hedera-nft-auction-demo-java-node && chmod +x gradlew
    - name: Build with Gradle
      env:
        OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
        OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}
        REFUND_KEY: ${{ secrets.OPERATOR_KEY }}
        #       Dragonglass only
        #        DG_API_KEY= // from secrets
        VUE_APP_NETWORK: testnet
        #       Run the REST API true/false
        REST_API: true
        VUE_APP_API_PORT: 8081
        API_VERTICLE_COUNT: 1
        #       Run the admin REST API true/false
        ADMIN_API: true
        ADMIN_API_PORT: 8082
        ADMIN_API_VERTICLE_COUNT: 1
        #       Run the Auction Node true/false
        AUCTION_NODE: true
        #       only if participating in refund transactions
        TRANSFER_ON_WIN: true
        #       auction topic details
        VUE_APP_TOPIC_ID:
        #       mirror node detail
        #       the mirror provider may be hedera, kabuto or dragonglass
        MIRROR_PROVIDER: hedera
        MIRROR_QUERY_FREQUENCY: 5000
        #       Database information for transaction and event logging
        DATABASE_URL: postgresql://localhost:5432/postgres
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: password
        #       Database information for transaction and event logging
        POOL_SIZE: 1
        #       REST Mirror urls
        REST_HEDERA_MAINNET: mainnet.mirrornode.hedera.com
        REST_HEDERA_TESTNET: testnet.mirrornode.hedera.com
        #        REST_HEDERA_PREVIEWNET: previewnet.mirrornode.hedera.com
        REST_HEDERA_PREVIEWNET: 162.222.182.83
        REST_KABUTO_MAINNET: api.kabuto.sh
        REST_KABUTO_TESTNET: api.testnet.kabuto.sh
        REST_KABUTO_PREVIEWNET:
        REST_DRAGONGLASS_MAINNET:
        REST_DRAGONGLASS_TESTNET:
        REST_DRAGONGLASS_PREVIEWNET:
        #       GRPC Mirror urls
        GRPC_HEDERA_MAINNET: hcs.mainnet.mirrornode.hedera.com:5600
        GRPC_HEDERA_TESTNET: hcs.testnet.mirrornode.hedera.com:5600
        #        GRPC_HEDERA_PREVIEWNET: hcs.previewnet.mirrornode.hedera.com:5600
        GRPC_HEDERA_PREVIEWNET: hcs.previewnet.mirrornode.hedera.com:5600
        GRPC_KABUTO_MAINNET: api.kabuto.sh:50211
        GRPC_KABUTO_TESTNET: api.testnet.kabuto.sh:50211
        GRPC_KABUTO_PREVIEWNET:
        GRPC_DRAGONGLASS_MAINNET: api.kabuto.sh:50211
        GRPC_DRAGONGLASS_TESTNET: api.testnet.kabuto.sh:50211
        GRPC_DRAGONGLASS_PREVIEWNET:
      run: cd hedera-nft-auction-demo-java-node && ./gradlew build testIntegration
